"component : avro":
 - kafka-avro/**/*
"component : reactor":
 - kafka-reactor/**/*
"component : sample":
 - kafka-sample/**/*
"component : streams":
 - kafka-streams/**/*

"status: waiting-for-triage":
  - ./*
  - ./**/*
"type: documentation": docs/**/*