"component : avro":
  - changed-files:
      - any-glob-to-any-file: 'kafka-avro/**/*'
"component : reactor":
  - changed-files:
      - any-glob-to-any-file: 'kafka-reactor/**/*'
"component : sample":
  - changed-files:
      - any-glob-to-any-file: 'kafka-sample/**/*'
"component : spring-boot":
  - changed-files:
      - any-glob-to-any-file: 'kafka-spring/**/*'
"component : streams":
  - changed-files:
      - any-glob-to-any-file: 'kafka-streams/**/*'
"type: documentation":
  - changed-files:
      - any-glob-to-any-file: 'docs/**/*'