name: analytics-spring-cloud-streams-kafka-producer

on:
  push:
    paths:
      - "analytics-spring-cloud-streams-kafka-producer/**"
    branches: [ master ]
  pull_request:
    paths:
      - "analytics-spring-cloud-streams-kafka-producer/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v3.2.0
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'
    - name: Build with Maven
      run: |
        cd analytics-spring-cloud-streams-kafka-producer
        mvn -B package --file pom.xml
