name: analytics-spring-cloud-streams-kafka-producer

on:
  push:
    paths:
      - "analytics-spring-cloud-streams-kafka-producer/**"
    branches: [ master ]
  pull_request:
    paths:
      - "analytics-spring-cloud-streams-kafka-producer/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "analytics-spring-cloud-streams-kafka-producer"
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v3.6.0
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'
    - name: Build with Maven
      run: ./mvnw -B clean verify --file pom.xml
