name: boot-kafka-reactor-producer

on:
  push:
    paths:
      - "kafka-reactor/boot-kafka-reactor-producer/**"
    branches: [ main ]
  pull_request:
    paths:
      - "kafka-reactor/boot-kafka-reactor-producer/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "kafka-reactor/boot-kafka-reactor-producer"
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v4.1.0
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: ./mvnw -B verify --file pom.xml
