name: kafka-sample-spring-cloud

on:
  push:
    paths:
      - "kafka-sample/spring-cloud/**"
    branches: [ main ]
  pull_request:
    paths:
      - "kafka-sample/spring-cloud/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "kafka-sample/spring-cloud"
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: ./mvnw -B verify --file pom.xml
