name: spring-boot-multiple-producers-consumers

on:
  push:
    paths:
      - "kafka-spring/spring-boot-multiple-producers-consumers/**"
    branches: [ main ]
  pull_request:
    paths:
      - "kafka-spring/spring-boot-multiple-producers-consumers/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run: 
          working-directory: kafka-spring/spring-boot-multiple-producers-consumers

    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v4.2.0
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: ./mvnw -B clean verify --file pom.xml
