name: kafka-sample-spring

on:
  push:
    paths:
      - "kafka-sample/spring/**"
    branches: [ master ]
  pull_request:
    paths:
      - "kafka-sample/spring/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "kafka-sample/spring"
    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v3.12.0
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
