name: kafka-sample-spring-boot

on:
  push:
    paths:
      - "kafka-sample/spring-boot/**"
    branches: [ main ]
  pull_request:
    paths:
      - "kafka-sample/spring-boot/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "kafka-sample/spring-boot"
    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        cache: 'maven'
        native-image-job-reports: 'true'
      
    - name: Printing versions
      run: |
        echo "GRAALVM_HOME: $GRAALVM_HOME"
        echo "JAVA_HOME: $JAVA_HOME"
        java --version
        native-image --version
    - name: Build with Maven
      run: ./mvnw -Pnative -B verify spring-boot:build-image --file pom.xml
