name: kafka-sample-spring-cloud

on:
  push:
    paths:
      - "kafka-sample/spring-cloud/**"
    branches: [ master ]
  pull_request:
    paths:
      - "kafka-sample/spring-cloud/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "kafka-sample/spring-cloud"
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v3.13.0
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'
    - name: Build with Maven
      run: ./mvnw -B verify --file pom.xml
