name: kafka-sample-spring-modulith-outbox-pattern

on:
  push:
    paths:
      - "kafka-sample/spring-modulith-outbox-pattern/**"
    branches: [ main ]
  pull_request:
    paths:
      - "kafka-sample/spring-modulith-outbox-pattern/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "kafka-sample/spring-modulith-outbox-pattern"
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v4.1.0
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B verify --file pom.xml
