name: spring-boot-kafka-dead-letter-publishing

on:
  push:
    paths:
      - "kafka-sample/spring-boot-kafka-dead-letter-publishing/**"
    branches: [ master ]
  pull_request:
    paths:
      - "kafka-sample/spring-boot-kafka-dead-letter-publishing/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "kafka-sample/spring-boot-kafka-dead-letter-publishing"
    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v3.11.0
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'
    - name: Build with Maven
      run: ./mvnw -B verify --file pom.xml
