name: spring-boot-multiple-producers-consumers

on:
  push:
    paths:
      - "kafka-sample/spring-boot-multiple-producers-consumers/**"
    branches: [ master ]
  pull_request:
    paths:
      - "kafka-sample/spring-boot-multiple-producers-consumers/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run: 
          working-directory: kafka-sample/spring-boot-multiple-producers-consumers

    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v3.13.0
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'
    - name: Build with Maven
      run: ./mvnw -B clean verify --file pom.xml
