name: spring-boot-multiple-producers-consumers

on:
  push:
    paths:
      - "spring-boot-multiple-producers-consumers/**"
    branches: [ master ]
  pull_request:
    paths:
      - "spring-boot-multiple-producers-consumers/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v3.1.0
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'
    - name: Build with Maven
      run: |
        cd spring-boot-multiple-producers-consumers
        mvn -B package --file pom.xml
