name: spring-boot-kafka-avro-consumer

on:
  push:
    paths:
      - "kafka-avro/spring-boot-kafka-avro-consumer/**"
    branches: [ main ]
  pull_request:
    paths:
      - "kafka-avro/spring-boot-kafka-avro-consumer/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "kafka-avro/spring-boot-kafka-avro-consumer"
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: 'maven'
    - name: Build with Maven
      run: ./mvnw -B clean verify --file pom.xml
