name: spring-boot-kafka-avro

on:
  push:
    paths:
      - "spring-boot-kafka-avro/**"
    branches: [ master ]
  pull_request:
    paths:
      - "spring-boot-kafka-avro/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v3.3.0
      with:
        java-version: '17'
        distribution: 'microsoft'
        cache: 'maven'
    - name: Start up kafka via Docker Compose
      run: |
        docker compose -f docker-compose-confluent.yml up -d
        sleep 10
        docker ps -a
    - name: Build with Maven
      run: |
        cd spring-boot-kafka-avro
        mvn -B package --file pom.xml
